# Generated by Django 3.0.8 on 2020-07-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_no',
            field=models.IntegerField(),
        ),
    ]
