# Generated by Django 3.0.8 on 2020-08-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200728_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Address',
            field=models.CharField(default='Your Address is currently is empty', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='First_name',
            field=models.CharField(default='Your First Name is currently is empty', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='P_no',
            field=models.IntegerField(default='Your Phone Number is currently is empty'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Your Last Name is currently is empty', max_length=50),
        ),
    ]
