# Generated by Django 3.0.8 on 2020-08-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20200824_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='P_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
