# Generated by Django 3.0.8 on 2021-06-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20210606_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
