# Generated by Django 3.0.8 on 2021-06-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20210606_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
    ]
