# Generated by Django 3.0.8 on 2021-06-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_profile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
