# Generated by Django 3.0.8 on 2021-06-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_auto_20210606_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='t_and_c',
            field=models.BooleanField(blank=True, null=True, verbose_name='Accepted terms'),
        ),
    ]
