# Generated by Django 3.0.8 on 2021-06-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_profile_t_and_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='t_and_c',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Accepted terms'),
        ),
    ]
