# Generated by Django 3.0.8 on 2021-06-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_auto_20210606_1941'),
        ('polls', '0002_auto_20210606_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='voter',
        ),
        migrations.AddField(
            model_name='petition',
            name='voter',
            field=models.ManyToManyField(to='Users.Profile'),
        ),
    ]
