# Generated by Django 3.0.8 on 2021-06-06 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210606_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_text', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateField(auto_now_add=True, verbose_name='Updated On')),
            ],
        ),
        migrations.AlterField(
            model_name='petition',
            name='agenda',
            field=models.ForeignKey(default = 1, on_delete=django.db.models.deletion.CASCADE, to='polls.Agenda'),
            preserve_default=False,
        ),
    ]
