# Generated by Django 3.0.8 on 2021-06-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210606_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='ends_on',
        ),
        migrations.AddField(
            model_name='agenda',
            name='ends_on',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
    ]
